title: "Communicating using Markdown"
description: "This course will walk you through everything you need to start organizing ideas and collaborating using Markdown, a lightweight language for text formatting."
template:
  name: "markdown-portfolio"
  repo: "communicating-using-md-template"
  
before:
- type: respond
  with: 01_first-response.md
  
steps:
Step 1:
- title: "Create a markdown file"
  description: "Make a pull request named Ny fil"
  event: check_run
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: Ny fil

Step 2:
- title: Create a h1 header
  description: Start the file with a `#` and the text of the header
  event: push
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: gate
    left: '%payload.pull_request.base.ref%'
    operator: ===
    right: main
    else:
    - type: respond
      with: 01_try-again.md
  - type: respond
    with: 01_nice-work.md
