title: "Communicating using Markdown"
description: "This course will walk you through everything you need to start organizing ideas and collaborating using Markdown, a lightweight language for text formatting."
template:
  name: "markdown-portfolio"
  repo: "communicating-using-md-template"

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: respond
  with: 01_first-response.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
Step 1: Lav en fil
- title: Create a markdown file
  description: Click on add file call it `file2.md`
  event: check_run
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: Ny fil

Step 2: Lav en header
- title: Create a h1 header
  description: Start the file with a `#` and the text of the header
  event: push
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: gate
    left: '%payload.pull_request.base.ref%'
    operator: ===
    right: main
    else:
    - type: respond
      with: 01_try-again.md
  - type: respond
    with: 01_nice-work.md

Step 3: Lav en h2
- title: Create a h2 header
  description: Below the h1 write the header starting the `##`
  event: pull_request.closed
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

Step 4: Lav et link
- title: Add a link to an external page
  description: Below the h2 create a link on the form `[Google](https://google.com)`
  event: release.published
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

Step 5: Lav et billede
- title: Add an image
  description: Below the link add picture on the form `![Google logo](https://google.com)`
  event: issue_comment.created
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

